application: voxlandhappy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  #mime_type: text/javascript
  static_dir: static

- url: /.*
  script: happy.app

- url: /bootstrap  
  static_dir: bootstrap

libraries:
- name: jinja2
  version: latest
